services:
  rabbitmq:
    image: rabbitmq:management
    container_name: broker-rabbitmq-3
    restart: always
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: welderessutti/ms-email:latest
    container_name: app-ms-email
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_MAIL_USERNAME: "welderessutti@gmail.com"
      SPRING_MAIL_PASSWORD: "mhfb hvad umnv zqet"
